theme: jekyll-theme-hacker
title: "Welcome to Platform9 curated applications catalog community"
description: "Platform9 Opensource Community for driving curated and certified applications via Helm and Operators"
repository: "git@github.com:platform9/certified-apps.git" 
baseurl: "https://platform9.com/open-source/"
logo: "/images/screen_applications-catalog2.png"  
date_format: "%B %-d, %Y"
read_time: true
words_per_minute: 200
mathjax: true
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"
google_analytics: # Google Analytics id, e.g. "UA-NNNNNNNN-N"
disqus:
  shortname: # Disqus shortname, e.g. "my_disqus_shortname"

# Liquid
liquid:
  error_mode: strict

# Build settings
markdown: kramdown
feed:
  path: atom.xml

# Pagination - https://jekyllrb.com/docs/pagination/
paginate: 10
paginate_path: /page:num/

# Search
search_full_content: false

# Taxonomy pages
category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

# Collections
collections:
  recipes:
    output: true
    permalink: /:collection/:path/

# Front Matter Defaults
defaults:
  # Post defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      comments: true
      share: true
  # Recipe defaults
  - scope:
      path: "_recipes"
      type: recipes
    values:
      layout: post
      comments: true
      share: true

# Site Author
author:
  name: Eric Bannon
  email: eric.bannon4@gmail.com
  twitter: Bannamal
  links:
    - title: Twitter
      url: https://twitter.com/Bannamal
      icon: fab fa-twitter-square
    - title: LinkedIn
      url: https://www.linkedin.com/in/ericbannon/
    - title: GitHub
      url: https://github.com/ericbannon
      icon: fab fa-github-square
